TRUNCATE TABLE MODEL;

/* === REGRESSION MODELS === */
INSERT INTO MODEL (NAME, CLASS_NAME, FAMILY) VALUES ('Linear Regression', 'LinearRegressionRegressor', 'REGRESSION');

/* === BINARY CLASSIFICATION MODELS === */
INSERT INTO MODEL (NAME, CLASS_NAME, FAMILY) VALUES ('Logistic Regression', 'LogisticRegressionBinaryClassifier', 'BINARY_CLASSIFICATION');

/* === MULTICLASS CLASSIFICATION MODELS === */
INSERT INTO MODEL (NAME, CLASS_NAME, FAMILY) VALUES ('Decision Tree', 'DecisionTreeMultiClassifier', 'MULTICLASS_CLASSIFICATION');
INSERT INTO MODEL (NAME, CLASS_NAME, FAMILY) VALUES ('Logistic Regression', 'LogisticRegressionMultiClassifier', 'MULTICLASS_CLASSIFICATION');
INSERT INTO MODEL (NAME, CLASS_NAME, FAMILY) VALUES ('Random Forest', 'RandomForestMultiClassifier', 'MULTICLASS_CLASSIFICATION');